### ISSUE TITLE
Store roscaCollectionTime as contract variable

### ISSUE THREAD

**Issue by morelazers** [WeTrustPlatform/rosca-contracts#101]
This prevents us from having to compute them in the functions themselves.

e.g. we don't need to calculate `roscaCollectionTime` in `endOfROSCARetrieveSurplus`, we could do it before the ROSCA even starts.

It would add a little cost to deployment, but saves WeTrust gas in the long run.

**Comment by shine2lay** [comment]
can you elaborate on how it saves WeTrust gas in the long run?

**Comment by morelazers** [comment]
WeTrust will be calling `endOfROSCARetrieveSurplus` right? We'll be supplying the gas to that function. It only saves a tiny bit of gas at the end of each ROSCA, so might not even be worth it considering the extra storage costs of contract variables

**Comment by shine2lay** [comment]
yeah, usually me and Ron have a lengthy discussion before adding a new contract variable. Just trying to make sure there is no easy alternative solution

**Comment by rmerom** [comment]
sorry, the documentation may not be clear enough. ```endOfROSCARetrieveSurplus``` is called by the founder. WeTrust calls ```endOfROSCARetrieveFees``` (or a similar name :) ).

What I'm not sure I understand though is why it would be hard for the FE to calculate when to do that, given it already calculated when to call ```startRound`` ?

**Comment by morelazers** [comment]
Oh, it shouldn't be a problem for the FE to calculate either - we can definitely have an automated collection. I was thinking about it this afternoon!
