### ISSUE TITLE
serviceFeeInThousandths

### ISSUE THREAD

**Issue by morelazers** [WeTrustPlatform/rosca-contracts#102]
Both places this variable is used there's a `/ 1000` operation. Consider storing the value in a different format so we don't have to do this.

**Comment by rmerom** [comment]
Unfortunately solidity (maybe also EVM) AFAIK does not support real numbers, so I'm not sure how to do that. Please do let us know if you think of a way.

**Comment by shine2lay** [comment]
@morelazers we are also aware that this operation could potentially introduce rounding errors, we already created an issue for that #80 .

**Comment by morelazers** [comment]
@shine2lay @rmerom sounds good 👍
