### ISSUE TITLE
Store roundStartTime multiplier as contract variable

### ISSUE THREAD

**Issue by morelazers** [WeTrustPlatform/rosca-contracts#103]
```
uint256 roundStartTime = startTime + (uint(currentRound)  * roundPeriodInDays * 1 days);
```

If we factor out the `roundPeriodInDays * 1 days` part of this to a contract variable, we have to do one less multiplication on startRound.

**Comment by rmerom** [comment]
That's a good observation, however contract variables are way more expensive from our tests than additional instructions.

**Comment by shine2lay** [comment]
+1 @rmerom. computations are significantly cheaper than storage variables.
