### ISSUE TITLE
no fees on totalDiscount

### ISSUE THREAD

**Issue by shine2lay** [WeTrustPlatform/rosca-contracts#110]
@rmerom , according to our google doc on fee structure 
https://docs.google.com/document/d/1AI5zGXCc2laO4rSlqh7KieQ1r4aMHbGWDUhAwbGuqW8/edit# 

we include fees on totalDiscount 
```  totalDiscounts += (DEFAULT_POT - potMoney) * (1 - feesRatio) / numParticipants; ```

but in our smart contract, totalDiscount is (DEFAULT_POT - potMoney) / numParticipants. 
either i missed this while reviewing the PR or did you have something else in mind?

I found out while trying to test the frontEnd.

**Comment by rmerom** [comment]
@shine2lay don't we take off fees in the contract?
https://github.com/WeTrustPlatform/rosca-contracts/blob/develop/contracts/ROSCA.sol#L284

**Comment by shine2lay** [comment]
you are right, i think the lack of sleep is getting to me

**Comment by shine2lay** [comment]
this means i have to go back to frontEnd and check
