### ISSUE TITLE
Upgrade contract to allow for 2 more types of ROSCAs

### ISSUE THREAD

**Issue by rmerom** [WeTrustPlatform/rosca-contracts#151]
* a lottery ROSCA, which is essentially the same as today's bidding ROSCA except it doesn't allow ROSCA.
* a pre-ordered ROSCA, where the order of recipients is pre-determined. This will likely require a change in the constructor API so that the owner is explicitly mentioned in the list of members (or can be omitted if wanted).

**Comment by shine2lay** [comment]
So for pre-ordered ROSCA, do we care if the chosen winner is delinquent? @rmerom

**Comment by rmerom** [comment]
(spoke about this offline)
For now, arbitrarily decide. @gliinbox will research into what's usually being done in other ROSCAs.

**Comment by shine2lay** [comment]
just to memorialize what's been discussed offline, for pre-ordered ROSCA, we don't care if the chosen winner is delinquent

**Comment by rmerom** [comment]
Yep
