### ISSUE TITLE
Emit currentRound in LogRoundFundsReleased 

### ISSUE THREAD

**Issue by blorange** [WeTrustPlatform/rosca-contracts#159]
Currently I don't think we can be fully sure which round this release was associated with without processing the events manually

thoughts @rmerom @shine2lay?

**Comment by rmerom** [comment]
We could certainly do that, but isn't it inferred from the previous `LogStartOfRound` ?
(and I can only guess the events are ordered by blocknumber?)

**Comment by blorange** [comment]
@rmerom yes, it could be inferred, but if we're processing events out of order (I don't know why we would be doing that, but it might happen), then we'd want to know which round it was for.

I guess the same could be said for most other `Log`s

**Comment by rmerom** [comment]
Yes, do you see a scenario where this might happen (processing events out of order)? if so then for sure let's add the round.

**Comment by blorange** [comment]
@rmerom I'm mainly thinking about the scenario where our watcher ends up missing any events for reasons known only to higher powers, and we have to manually reprocess events.

I would like to implement a kind of 'failsafe' wherein events are fetched from the contract and processed every so often, maybe once per day. This doesn't sound particularly scalable I know, but after hearing reports of event watchers skipping events in other projects, it would be good to make sure we're not leaving ourselves open to that possibility.

Let's say one event is skipped over the course of a day, any processing of it will be out-of-context due to the current setup of the eventwatcher and other components, which expects events to come through in order.

I'm hoping that this is a step towards a more permanent solution, and I'm even considering some form of 'ondemand' event processing, wherein actions performed from the dapp interface cause us to poll the contract for any new events (or even just start a short-term watcher), timing out after a minute or two if we don't find one. This way we're not relying on constant watchers at all (and can nicely handle the 'I did something but the system hasn't changed state yet' scenarios), though it does still require us to solve the issue of our nodes dropping off.

We should have a conversation about the possible options some time this week. In the meantime I will continue trying to solve the issues with the node and cleaning up the MVP codebase.

**Comment by rmerom** [comment]
Yeah, this makes a lot of sense.
However, if we can't rely on collecting all the events, I believe we might screw up in different ways (e.g. missing some bids, missing start of rounds etc.). This would require us to maybe have logic more complex than needed. 
I'm wondering if we put enough effort into it, like some of the ideas you mentioned, if we cannot arrive at a dependable solution? 
I'm also all in for the "daily failsafe" option, but I think we need to get to the place where relying on this is the exception, not the rule. wdyt?

**Comment by shine2lay** [comment]
done
