### ISSUE TITLE
[Question] should we check that foreperson is in the member's list?

### ISSUE THREAD

**Issue by shine2lay** [WeTrustPlatform/rosca-contracts#181]
Context: we used to count the contract creator as foreperson automatically and added him/her as a member. But when we added `PRE-DETERMINED` rosca type, we change this so that the order of the memberlist is the payout list. 

I just noticed that we never check whether the creator `msg.sender` is in the member list. Is it something we should add? ** note this this would add extra gas usage ** 

@jusx @sihoang @tdimopoulos.

**Comment by sihoang** [comment]
It's better to add the check to make sure it's consistent with the requirement which foreperson must be in the member list.

**Comment by jusx** [comment]
@shine2lay IMO we should validate. I agree with Hoang. 

Can you explain how/why this would add extra gas cost?

**Comment by shine2lay** [comment]
@jusx 
every line of code executed = more gas, so it is optimal to use as few lines of code as possible.

**Comment by jusx** [comment]
Interesting. I was curious so I went looking for details
https://hackernoon.com/costs-of-a-real-world-ethereum-contract-2033511b3214
