### ISSUE TITLE
Write a test that checks fees are calculated on interim contributions

### ISSUE THREAD

**Issue by rmerom** [WeTrustPlatform/rosca-contracts#61]
p0 is the only one who contributed in round 1 (everyone else delinquent)
make sure that in round 2 p0 needs to contribute the extra fees

**Comment by rmerom** [comment]
@shine2lay I opened this after our talk today, and wanted to write a test for that, but I'm not sure what we mean in terms of behavior (as opposed to internal state). Do you see a test that needs to be written for that, or should I close this issue?

**Comment by shine2lay** [comment]
The only behavior i can think of to test would be to check how much fees is actually collected similar to other fees unit test case, I've written this test, i'll add it in the next PR

**Comment by shine2lay** [comment]
#58 included this test
