### ISSUE TITLE
Create an NPM method for retrieving ROSCA contract

### ISSUE THREAD

**Issue by rmerom** [WeTrustPlatform/rosca-contracts#74]

**Comment by rmerom** [comment]
from @anzheng67 :
"actually, it would be greater in the module can give us compiled code and/or abi as well"

/sub @morelazers

**Comment by anzheng67** [comment]
something like var rosca = require('wetrust-rosca-contract');
rosca.getAbi
rosca.getSol
...

**Comment by rmerom** [comment]
#79
