### ISSUE TITLE
withdrawal() does not work as expected?

### ISSUE THREAD

**Issue by anzheng67** [WeTrustPlatform/rosca-contracts#86]
I am not sure if this a bug in the backend or not and just create this for keeping track.

Context:
10 Eth pool, 2 participants.  Each contributes 5 Eth per round.
After winning first round, the member calls withdraw() and it only gets ~5 Eth.  Expected to be ~10 Eth

**Comment by rmerom** [comment]
Thanks An! Please note https://github.com/anzheng67/rosca-mvp/issues/71 . Could you upgrade wetrust-rosca-contract to 0.0.7 and try again?

**Comment by anzheng67** [comment]
@rmerom thanks!

**Comment by shine2lay** [comment]
@anzheng67 please let us know if it works or not, so can we can decide either to check for bugs or close this issue. Thanks

**Comment by anzheng67** [comment]
I am closing this issue.  Front end needs to explain to users how much they can withdraw
